services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - user-service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=codeinterviewhub
      - DB_SCHEMA=user_schema
    volumes:
      - ./user-service:/app
      - /app/node_modules
    command: ["bun", "run", "dev"]
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeinterviewhub

    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
